### ISSUE TITLE
Functions for C compatible library calls.

### ISSUE THREAD

**Issue by majorendian** [philiprbrenan/NasmX86#24]
Routines to allow interfacing with C code

**Comment by philiprbrenan** [comment]
Golly: this is amazing.  Jolly well done. I have added your impressive code to the mainline of development. And it works, see Assemble 83 in:

https://github.com/philiprbrenan/NasmX86/runs/2675167842?check_suite_focus=true

And all this was done on just an android phone? 

I have no idea why pushing a byte of **0xa1** to the stack aligns it correctly - do we need an auto stack align capability so that users can do this easily?

And why **ld** relies on an interpreter is not obvious either - how did you find out all this surprising information?  Is it the same across all Linuxes? 

I would have thought that this would be impossible to do without first doing the initialization done in a **C** **main** function - but this does not seem to necessary?

How are users going to code new line characters in format strings?

I am most impressed - congratulations on a job well done!

**Comment by majorendian** [comment]
I am using a tablet with a micro-usb keyboard and developing this on my server inzerts.com (currently not much happens there).
The 0xa1 stands for "align" but it could be any number. The important part is that the stack must always be 16 byte align otherwise it causes a segmentation fault.
Check: https://stackoverflow.com/questions/24991944/linking-c-with-nasm
It isn't 100% finished due to this. We keep pushing and poping a lot of registers on the stack. So in order for me to make this work I just pushed a value on the stack to align it. If I understand correctly RSP must be divisible by 16 in order for this to work. So we'll have to keep track of the number of pushes and pops. The sde64 emulator helped me greatly in identifing this issue.
Also, I am doing this from a hospital :)

**Comment by philiprbrenan** [comment]
I have added auto stack alignment to the main branch, please see the code at:
```
sub CallC($@)                                                                   # Call a C subroutine
```
and

```
#TCallC
```

**Comment by philiprbrenan** [comment]
How are users going to code new line characters in format strings?

I have upgraded **sub Rs** so that special characters are represented as decimal codes which have no corresponding side effects.

**Comment by majorendian** [comment]
I have update test 24 to reflect this change and it works as expected.
Could I ask you to please use the pull requests I am making and merge them? Or would you prefer if I make them from my fork? Or would you prefer if I just send you a patch file? Or just send you the file via email or an issue here on github?

**Comment by philiprbrenan** [comment]
If I may express a preference it would be as follows:  please mark the
areas in which you have made changes with *#ATino* and then send me the
whole file. This will allow me to understand your esteemed work in situ.

**Comment by majorendian** [comment]
Alright! I will do as you request.

**Comment by philiprbrenan** [comment]
Exports list updated.

I have updated the suggested code for marking your improvements to #ATino  - the * was an attempt at markup that did not work.

**Comment by philiprbrenan** [comment]
README.md updated to include the latest demonstration of calling C functions.
